-- 1. Show All Inventory Items
SELECT
    ITEM_ID,
    NAME,
    CATEGORY,
    QUANTITY_ON_HAND,
    REORDER_LEVEL
FROM ITEM
ORDER BY CATEGORY, NAME;
-- 2. Find Inventory Items That Need to Be Reordered
SELECT
    ITEM_ID,
    NAME,
    QUANTITY_ON_HAND,
    REORDER_LEVEL
FROM ITEM
WHERE CATEGORY = 'SUPPLY'
  AND REORDER_LEVEL IS NOT NULL
  AND QUANTITY_ON_HAND <= REORDER_LEVEL
ORDER BY QUANTITY_ON_HAND;
-- 3. Show Which Suppliers Provide Each Item and the Unit Cost
SELECT
    s.NAME AS SUPPLIER_NAME,
    i.NAME AS ITEM_NAME,
    si.UNIT_COST
FROM SUPPLIER_ITEM si
JOIN SUPPLIER s
    ON si.SUPPLIER_ID = s.SUPPLIER_ID
JOIN ITEM i
    ON si.ITEM_ID = i.ITEM_ID
ORDER BY i.NAME, si.UNIT_COST;
-- 4. Show All Purchase Orders with Supplier Information
SELECT
    po.PURCHASE_ORDER_ID,
    s.NAME AS SUPPLIER_NAME,
    po.ORDER_DATE,
    po.STATUS
FROM PURCHASE_ORDER po
JOIN SUPPLIER s
    ON po.SUPPLIER_ID = s.SUPPLIER_ID
ORDER BY po.ORDER_DATE;
5. Show the Details of Each Purchase Order
SELECT
    po.PURCHASE_ORDER_ID,
    s.NAME AS SUPPLIER_NAME,
    i.NAME AS ITEM_NAME,
    pod.QUANTITY,
    si.UNIT_COST,
    (pod.QUANTITY * si.UNIT_COST) AS TOTAL_COST
FROM PURCHASE_ORDER_DETAIL pod
JOIN PURCHASE_ORDER po
    ON pod.PURCHASE_ORDER_ID = po.PURCHASE_ORDER_ID
JOIN SUPPLIER s
    ON po.SUPPLIER_ID = s.SUPPLIER_ID
JOIN ITEM i
    ON pod.ITEM_ID = i.ITEM_ID
JOIN SUPPLIER_ITEM si
    ON po.SUPPLIER_ID = si.SUPPLIER_ID
   AND pod.ITEM_ID = si.ITEM_ID
ORDER BY po.PURCHASE_ORDER_ID;
-- 6. Check Supplier Delivery Performance
SELECT
    s.NAME AS SUPPLIER_NAME,
    po.PURCHASE_ORDER_ID,
    pod.EXPECTED_DATE,
    pod.ACTUAL_DATE,
    CASE
        WHEN pod.ACTUAL_DATE IS NULL THEN 'NOT DELIVERED'
        WHEN pod.ACTUAL_DATE <= pod.EXPECTED_DATE THEN 'ON TIME'
        ELSE 'LATE'
    END AS DELIVERY_STATUS
FROM PURCHASE_ORDER_DELIVERY pod
JOIN PURCHASE_ORDER po
    ON pod.PURCHASE_ORDER_ID = po.PURCHASE_ORDER_ID
JOIN SUPPLIER s
    ON po.SUPPLIER_ID = s.SUPPLIER_ID
ORDER BY pod.EXPECTED_DATE;
-- 7. Calculate Supplier On-Time Delivery Percentage
SELECT
    s.NAME AS SUPPLIER_NAME,
    COUNT(pod.PURCHASE_ORDER_DELIVERY_ID) AS TOTAL_DELIVERIES,
    SUM(
        CASE
            WHEN pod.ACTUAL_DATE <= pod.EXPECTED_DATE THEN 1
            ELSE 0
        END
    ) AS ON_TIME_DELIVERIES,
    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN pod.ACTUAL_DATE <= pod.EXPECTED_DATE THEN 1
                ELSE 0
            END
        ) / COUNT(pod.PURCHASE_ORDER_DELIVERY_ID),
        2
    ) AS ON_TIME_PERCENTAGE
FROM SUPPLIER s
JOIN PURCHASE_ORDER po
    ON s.SUPPLIER_ID = po.SUPPLIER_ID
JOIN PURCHASE_ORDER_DELIVERY pod
    ON po.PURCHASE_ORDER_ID = pod.PURCHASE_ORDER_ID
WHERE pod.ACTUAL_DATE IS NOT NULL
GROUP BY s.SUPPLIER_ID, s.NAME
ORDER BY ON_TIME_PERCENTAGE DESC;
-- 8. Show Which Products Each Distributor Carries
SELECT
    d.NAME AS DISTRIBUTOR_NAME,
    i.NAME AS PRODUCT_NAME
FROM DISTRIBUTOR_ITEM di
JOIN DISTRIBUTOR d
    ON di.DISTRIBUTOR_ID = d.DISTRIBUTOR_ID
JOIN ITEM i
    ON di.ITEM_ID = i.ITEM_ID
WHERE i.CATEGORY = 'PRODUCT'
ORDER BY d.NAME, i.NAME;
-- 9. Show All Sales Orders and Their Distributors
SELECT
    so.SALES_ORDER_ID,
    d.NAME AS DISTRIBUTOR_NAME,
    so.ORDER_DATE,
    so.STATUS
FROM SALES_ORDER so
JOIN DISTRIBUTOR d
    ON so.DISTRIBUTOR_ID = d.DISTRIBUTOR_ID
ORDER BY so.ORDER_DATE;
10. Show Product Sales by Wine
SELECT
    i.NAME AS WINE,
    SUM(sod.QUANTITY) AS TOTAL_UNITS_SOLD
FROM SALES_ORDER_DETAIL sod
JOIN ITEM i
    ON sod.ITEM_ID = i.ITEM_ID
WHERE i.CATEGORY = 'PRODUCT'
GROUP BY i.ITEM_ID, i.NAME
ORDER BY TOTAL_UNITS_SOLD DESC;
-- 11. Show Sales by Distributor and Product
SELECT
    d.NAME AS DISTRIBUTOR_NAME,
    i.NAME AS WINE,
    SUM(sod.QUANTITY) AS TOTAL_QUANTITY
FROM SALES_ORDER so
JOIN DISTRIBUTOR d
    ON so.DISTRIBUTOR_ID = d.DISTRIBUTOR_ID
JOIN SALES_ORDER_DETAIL sod
    ON so.SALES_ORDER_ID = sod.SALES_ORDER_ID
JOIN ITEM i
    ON sod.ITEM_ID = i.ITEM_ID
WHERE i.CATEGORY = 'PRODUCT'
GROUP BY d.DISTRIBUTOR_ID, d.NAME, i.ITEM_ID, i.NAME
ORDER BY d.NAME, TOTAL_QUANTITY DESC;
-- 12. Show All Shipments and Their Status
SELECT
    sos.SALES_ORDER_SHIPMENT_ID,
    d.NAME AS DISTRIBUTOR_NAME,
    sos.SALES_ORDER_ID,
    sos.SHIPMENT_DATE,
    sos.DELIVERY_DATE,
    sos.STATUS
FROM SALES_ORDER_SHIPMENT sos
JOIN SALES_ORDER so
    ON sos.SALES_ORDER_ID = so.SALES_ORDER_ID
JOIN DISTRIBUTOR d
    ON so.DISTRIBUTOR_ID = d.DISTRIBUTOR_ID
ORDER BY sos.SALES_ORDER_SHIPMENT_ID;
-- 13. Find Shipments That Have Not Been Delivered
SELECT
    sos.SALES_ORDER_SHIPMENT_ID,
    d.NAME AS DISTRIBUTOR_NAME,
    so.SALES_ORDER_ID,
    sos.SHIPMENT_DATE,
    sos.STATUS
FROM SALES_ORDER_SHIPMENT sos
JOIN SALES_ORDER so
    ON sos.SALES_ORDER_ID = so.SALES_ORDER_ID
JOIN DISTRIBUTOR d
    ON so.DISTRIBUTOR_ID = d.DISTRIBUTOR_ID
WHERE sos.DELIVERY_DATE IS NULL
ORDER BY sos.SHIPMENT_DATE;
-- 14. Show Employee Time Entries
SELECT
    e.EMPLOYEE_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.JOB_TITLE,
    te.WORK_DATE,
    te.HOURS_WORKED
FROM EMPLOYEE e
JOIN TIME_ENTRY te
    ON e.EMPLOYEE_ID = te.EMPLOYEE_ID
ORDER BY te.WORK_DATE, e.LAST_NAME;
-- 15. Total Hours Worked by Employee
SELECT
    e.EMPLOYEE_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.JOB_TITLE,
    SUM(te.HOURS_WORKED) AS TOTAL_HOURS
FROM EMPLOYEE e
JOIN TIME_ENTRY te
    ON e.EMPLOYEE_ID = te.EMPLOYEE_ID
GROUP BY
    e.EMPLOYEE_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.JOB_TITLE
ORDER BY TOTAL_HOURS DESC;
-- 16. Employee Hours by Quarter
SELECT
    e.FIRST_NAME,
    e.LAST_NAME,
    YEAR(te.WORK_DATE) AS WORK_YEAR,
    QUARTER(te.WORK_DATE) AS WORK_QUARTER,
    SUM(te.HOURS_WORKED) AS TOTAL_HOURS
FROM EMPLOYEE e
JOIN TIME_ENTRY te
    ON e.EMPLOYEE_ID = te.EMPLOYEE_ID
GROUP BY
    e.EMPLOYEE_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    YEAR(te.WORK_DATE),
    QUARTER(te.WORK_DATE)
ORDER BY
    WORK_YEAR,
    WORK_QUARTER,
    e.LAST_NAME;

