SELECT
    d.NAME AS DISTRIBUTOR_NAME,
    i.NAME AS PRODUCT_NAME
FROM DISTRIBUTOR_ITEM di
JOIN DISTRIBUTOR d
    ON di.DISTRIBUTOR_ID = d.DISTRIBUTOR_ID
JOIN ITEM i
    ON di.ITEM_ID = i.ITEM_ID
WHERE i.CATEGORY = 'PRODUCT'
ORDER BY d.NAME, i.NAME;