SELECT
    RESULTS.WINE,
    RESULTS.DISTRIBUTOR,
    RESULTS.TOTAL_UNITS_SOLD
FROM (
    SELECT
        I.NAME AS WINE,
        D.NAME AS DISTRIBUTOR,
        COALESCE(SUM(SOD.QUANTITY), 0) AS TOTAL_UNITS_SOLD,
        1 AS SORT_ORDER
    FROM DISTRIBUTOR_ITEM DI
    JOIN DISTRIBUTOR D
        ON DI.DISTRIBUTOR_ID = D.DISTRIBUTOR_ID
    JOIN ITEM I
        ON DI.ITEM_ID = I.ITEM_ID
    LEFT JOIN SALES_ORDER SO
        ON D.DISTRIBUTOR_ID = SO.DISTRIBUTOR_ID
    LEFT JOIN SALES_ORDER_DETAIL SOD
        ON SO.SALES_ORDER_ID = SOD.SALES_ORDER_ID
        AND SOD.ITEM_ID = I.ITEM_ID
    WHERE I.CATEGORY = 'PRODUCT'
    GROUP BY
        I.ITEM_ID,
        I.NAME,
        D.DISTRIBUTOR_ID,
        D.NAME

    UNION ALL

    SELECT
        I.NAME AS WINE,
        'TOTAL' AS DISTRIBUTOR,
        COALESCE(SUM(SOD.QUANTITY), 0) AS TOTAL_UNITS_SOLD,
        2 AS SORT_ORDER
    FROM ITEM I
    LEFT JOIN SALES_ORDER_DETAIL SOD
        ON I.ITEM_ID = SOD.ITEM_ID
    WHERE I.CATEGORY = 'PRODUCT'
    GROUP BY
        I.ITEM_ID,
        I.NAME
) RESULTS
ORDER BY
    RESULTS.SORT_ORDER,
    RESULTS.WINE,
    RESULTS.DISTRIBUTOR;