SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    YEAR(TE.WORK_DATE) AS WORK_YEAR,
    QUARTER(TE.WORK_DATE) AS WORK_QUARTER,
    SUM(TE.HOURS_WORKED) AS TOTAL_HOURS
FROM EMPLOYEE E
JOIN TIME_ENTRY TE
    ON E.EMPLOYEE_ID = TE.EMPLOYEE_ID
GROUP BY
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    YEAR(TE.WORK_DATE),
    QUARTER(TE.WORK_DATE)
ORDER BY
    E.LAST_NAME,
    E.FIRST_NAME,
    WORK_YEAR,
    WORK_QUARTER;