SELECT
    s.NAME AS SUPPLIER_NAME,
    po.PURCHASE_ORDER_ID,
    pod.EXPECTED_DATE,
    pod.ACTUAL_DATE,
    DATEDIFF(
        pod.ACTUAL_DATE,
        pod.EXPECTED_DATE
    )  AS DAYS_LATE,
    CASE
        WHEN pod.ACTUAL_DATE IS NULL THEN 'NOT DELIVERED'
        WHEN pod.ACTUAL_DATE <= pod.EXPECTED_DATE THEN 'ON TIME'
        ELSE 'LATE'
    END AS DELIVERY_STATUS
FROM PURCHASE_ORDER po
JOIN PURCHASE_ORDER_DELIVERY pod
    ON pod.PURCHASE_ORDER_ID = po.PURCHASE_ORDER_ID
JOIN SUPPLIER s
    ON po.SUPPLIER_ID = s.SUPPLIER_ID
ORDER BY pod.EXPECTED_DATE;