SELECT
    s.NAME AS SUPPLIER_NAME,
    COUNT(pod.PURCHASE_ORDER_DELIVERY_ID) AS TOTAL_DELIVERIES,
    SUM(
        CASE
            WHEN pod.ACTUAL_DATE <= pod.EXPECTED_DATE THEN 1
            ELSE 0
        END
    ) AS ON_TIME_DELIVERIES,
    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN pod.ACTUAL_DATE <= pod.EXPECTED_DATE THEN 1
                ELSE 0
            END
        ) / COUNT(pod.PURCHASE_ORDER_DELIVERY_ID),
        2
    ) AS ON_TIME_PERCENTAGE
FROM SUPPLIER s
JOIN PURCHASE_ORDER po
    ON s.SUPPLIER_ID = po.SUPPLIER_ID
JOIN PURCHASE_ORDER_DELIVERY pod
    ON po.PURCHASE_ORDER_ID = pod.PURCHASE_ORDER_ID
WHERE pod.ACTUAL_DATE IS NOT NULL
GROUP BY s.SUPPLIER_ID, s.NAME
ORDER BY ON_TIME_PERCENTAGE DESC;