SELECT
    i.NAME AS SUPPLY,
    i.QUANTITY_ON_HAND,
    i.REORDER_LEVEL,
    i.QUANTITY_ON_HAND - i.REORDER_LEVEL AS UNITS_ABOVE_REORDER,
    CASE
        WHEN i.QUANTITY_ON_HAND - i.REORDER_LEVEL < 0
            THEN 'NEEDS REORDERED'
        WHEN i.QUANTITY_ON_HAND - i.REORDER_LEVEL = 0
            THEN 'AT REORDER LEVEL'
        ELSE 'OK'
    END AS REORDER_STATUS
FROM ITEM i
WHERE i.CATEGORY = 'SUPPLY'
  AND i.REORDER_LEVEL IS NOT NULL
ORDER BY
    UNITS_ABOVE_REORDER;